// Build-time translation dictionary, harvested verbatim from the retired
// js/i18n.js runtime switcher. Every key has both EN and DE — parity was
// verified at extraction time and is asserted by tests/i18n.spec.js.
//
// Usage in templates: {{ t['hero.title1'] }} — `t` is bound to the page's
// language by the `lang` pagination in each template's front matter.
export default {
  en: {
    "about.badge": "Average rating from 528 verified reviews",
    "about.certs.eyebrow": "Credentials",
    "about.certs.subtitle": "The boring paperwork that lets you sleep at night. We've done all of it.",
    "about.certs.title": "Certified, insured, audited",
    "about.cta": "Meet the team",
    "about.desc": "Founded in 2010 in a single Düsseldorf apartment, BlitzBlank has grown into the Rhine-Ruhr region's most quietly trusted cleaning studio. We refuse to franchise. Every crew is hired, trained, and equipped in-house — because quality is something you can't outsource.",
    "about.exp.1.label": "Years in Business",
    "about.exp.2.label": "Crew Members",
    "about.exp.3.label": "Cleans Completed",
    "about.exp.4.label": "Client Retention",
    "about.exp.eyebrow": "By the Numbers",
    "about.exp.title": "Fifteen years, told in figures",
    "about.eyebrow": "Our Story",
    "about.f1.desc": "Background-checked, uniformed, and trained for 80 hours before stepping into your space.",
    "about.f1.title": "Vetted Crews",
    "about.f2.desc": "Plant-based, pH-neutral products that are safe for kids, pets, and the planet.",
    "about.f2.title": "Eco-First",
    "about.f3.desc": "Not happy with a clean? We return within 24 hours to make it right, free.",
    "about.f3.title": "Real Guarantee",
    "about.f4.desc": "Flat-rate quotes online in 60 seconds. No surprises, no upsells, no nickel-and-diming.",
    "about.f4.title": "Transparent Pricing",
    "about.head.eyebrow": "About Us",
    "about.head.subtitle": "Our mission, our vision, and the five values we measure every decision against.",
    "about.head.title": "The team behind the shine",
    "about.mission.text": "To elevate the standard of cleaning in every home and business we touch — proving that a spotless space is not a luxury, but a foundation for clearer thinking, calmer living, and more productive work. We exist to give people their time back, and a space they're proud of.",
    "about.mission.title": "Our Mission",
    "about.mv.eyebrow": "What Drives Us",
    "about.mv.subtitle": "Two short sentences that shape every decision we make.",
    "about.mv.title": "Our mission & vision",
    "about.team.eyebrow": "The People",
    "about.team.subtitle": "The hands-on crew behind every spotless space. You'll see them on site — not behind a desk.",
    "about.team.title": "Meet the leadership team",
    "about.timeline.eyebrow": "Our Journey",
    "about.timeline.subtitle": "From a single Düsseldorf apartment to the Rhine-Ruhr's most quietly trusted cleaning studio.",
    "about.timeline.title": "Fifteen years, one obsession",
    "about.title": "A boutique studio, not a faceless franchise.",
    "about.value.1.text": "We do what we said we'd do, exactly when we said we'd do it. If we mess up, we say so — and we fix it, fast, no excuses.",
    "about.value.1.title": "Integrity",
    "about.value.2.text": "Cleaning is not a chore to us — it's a craft. We study tools, techniques, and chemistry so you don't have to think about any of it.",
    "about.value.2.title": "Craft",
    "about.value.3.text": "We treat every space as if it were our own. Your home, your office, your restaurant — it matters to us because it matters to you.",
    "about.value.3.title": "Care",
    "about.value.4.text": "You'll never have to wonder if we're showing up. Same crew, same time, same spotless result — visit after visit, year after year.",
    "about.value.4.title": "Reliability",
    "about.value.5.text": "Plant-based products, refillable bottles, electric vehicles. We obsess over our environmental footprint as much as your dust bunnies.",
    "about.value.5.title": "Sustainability",
    "about.values.eyebrow": "What We Stand For",
    "about.values.subtitle": "These aren't posters on a wall. They're the filters we run every decision through.",
    "about.values.title": "Five values, lived daily",
    "about.vision.text": "To become the Rhein-Ruhr region's most quietly trusted cleaning studio — known not for marketing volume, but for the calibre of our crews, the rigour of our training, and the relationships we build with each client.",
    "about.vision.title": "Our Vision",
    "contact.address.label": "Studio HQ",
    "contact.details.desc": "Prefer to talk first? Call us, email us, or stop by the Düsseldorf HQ. We answer every message ourselves — no chatbots, no offshore call centres.",
    "contact.details.eyebrow": "Contact Details",
    "contact.details.title": "Real people, real fast responses.",
    "contact.email.label": "Email",
    "contact.faq.btn1": "Visit FAQ",
    "contact.faq.btn2": "View services",
    "contact.faq.desc": "Browse our most-asked questions — we cover products, scheduling, guarantees, and more.",
    "contact.faq.title": "Have a quick question first?",
    "contact.form.consent": "I agree to be contacted about my request and accept the",
    "contact.form.consent.cont": "We never share your data.",
    "contact.form.consent.privacy": "privacy policy",
    "contact.form.desc": "Fields marked with * are required. We respond within one business day.",
    "contact.form.email": "Email",
    "contact.form.firstName": "First name",
    "contact.form.lastName": "Last name",
    "contact.form.message": "Tell us about your space",
    "contact.form.message.ph": "Square footage, frequency, any specific concerns…",
    "contact.form.phone": "Phone",
    "contact.form.service": "Service needed",
    "contact.form.service.choose": "Please choose…",
    "contact.form.service.other": "Other / Not sure",
    "contact.form.submit": "Send my request",
    "contact.form.title": "Request your free quote",
    "contact.hours.label": "Business Hours",
    "contact.hours.value": "Mon–Sat: 7:00 AM – 8:00 PM",
    "contact.hours.value2": "Sunday: Closed (emergencies only)",
    "contact.map.eyebrow": "Find Us",
    "contact.map.parking": "Parking nearby",
    "contact.map.subtitle": "Drop by for a coffee, or schedule a tour of the studio where every clean begins.",
    "contact.map.title": "Our Königsallee HQ",
    "contact.phone.label": "Phone",
    "crumb.home": "Home",
    "crumb.label": "Breadcrumb",
    "cta.btn1": "Get my free quote",
    "cta.btn2": "Call us",
    "cta.desc": "Get a personalised quote in under 60 seconds. No obligations, no pressure — just a real conversation about what your space needs.",
    "cta.eyebrow": "Ready When You Are",
    "cta.title": "Let's make your space immaculate.",
    "error.btn1": "Back to home",
    "error.btn2": "Browse services",
    "error.btn3": "Contact us",
    "error.code": "404",
    "error.desc": "Even our crews can't clean up a missing page. The link you followed may be broken, or the page may have been moved. Let's get you back to a spotless place.",
    "error.suggest": "Or try one of these",
    "error.suggest.about": "About Us",
    "error.suggest.faq": "FAQ",
    "error.suggest.gallery": "Gallery",
    "error.suggest.reviews": "Reviews",
    "error.title": "This page slipped away.",
    "faq.1.a": "Absolutely. Every product in our kit is plant-based, pH-neutral, and certified by the EU Ecolabel. No bleach, no ammonia, no harsh solvents. Our crews are trained to keep all supplies sealed and out of reach during cleaning. We also offer fully hypoallergenic options on request for clients with sensitivities.",
    "faq.1.q": "Are your cleaning products safe for kids and pets?",
    "faq.2.a": "Not at all. Most of our clients are at work during their scheduled cleaning. We use secure key-holding protocols, and every crew member is background-checked and bonded. If you prefer to be home, that's fine too — our crews are friendly, uniformed, and respectful of your space.",
    "faq.2.q": "Do I need to be home during the cleaning?",
    "faq.3.a": "We back every clean with a 100% satisfaction guarantee. If anything is less than perfect, contact us within 24 hours and we'll return to re-clean the affected areas at no charge — no questions, no awkwardness. We've issued this guarantee since 2010 and it's the foundation of our reputation.",
    "faq.3.q": "What happens if I'm not satisfied with the result?",
    "faq.4.a": "We use flat-rate pricing based on square metres, room count, and the scope of work — never hourly. You'll receive a written quote within 60 seconds via our online form, and the price you see is the price you pay. No surprise add-ons, no tip pressure, no nickel-and-diming.",
    "faq.4.q": "How do you price your services?",
    "faq.5.a": "Yes — weekly, bi-weekly, and monthly recurring cleanings are our most popular plans. Recurring clients enjoy locked-in rates, priority scheduling, and the same crew every visit whenever possible. You can pause, skip, or cancel any time with 48 hours' notice, no contracts required.",
    "faq.5.q": "Can I schedule recurring cleanings?",
    "faq.6.a": "Yes, fully. BlitzBlank carries €2 million in general liability insurance, workers' compensation for every employee, and a fidelity bond covering theft or damage. Certificates of insurance are available on request — we'll happily add your property as an additional insured for commercial engagements.",
    "faq.6.q": "Are you insured and bonded?",
    "faq.eyebrow": "Good to Know",
    "faq.subtitle": "Everything you need to know before booking. Still curious? Just reach out — we love to chat.",
    "faq.title": "Frequently asked questions",
    "footer.about": "Boutique cleaning studio serving Düsseldorf and the Rhine-Ruhr region since 2010. Obsessive attention to detail, eco-friendly products, real people who care.",
    "footer.backToTop": "Back to top",
    "footer.imprint": "Legal Notice",
    "footer.newsletter": "Stay in touch",
    "footer.newsletterDesc": "Subscribe for seasonal cleaning tips, exclusive offers, and the occasional dose of inspiration. No spam, ever.",
    "footer.placeholder": "Your email address",
    "footer.privacy": "Privacy",
    "footer.quickLinks": "Quick Links",
    "footer.rights": "BlitzBlank. All rights reserved.",
    "footer.services": "Services",
    "footer.subscribe": "Subscribe",
    "form.checked": "Please check this box to continue.",
    "form.email": "Please enter a valid email address.",
    "form.errorMsg": "Please correct the highlighted fields and try again.",
    "form.minLength": "Please enter at least {n} characters.",
    "form.phone": "Please enter a valid phone number.",
    "form.required": "This field is required.",
    "form.sendError": "Your message could not be sent. Please try again in a moment, or email us directly.",
    "form.subject": "New contact request via blitzblank.de",
    "form.successMsg": "Thank you! Your message has been sent. We'll get back to you within one business day.",
    "form.toast.invalid": "Please enter a valid email address.",
    "form.toast.sendError": "Sending failed — please try again.",
    "form.toast.subscribed": "You're subscribed! Welcome aboard.",
    "form.toast.success": "Message sent successfully!",
    "gallery.cat1": "Residential",
    "gallery.cat2": "Commercial",
    "gallery.cat3": "Deep Clean",
    "gallery.cat4": "Floor Care",
    "gallery.cat5": "Hospitality",
    "gallery.cta": "View full gallery",
    "gallery.cta.btn1": "Start your project",
    "gallery.cta.btn2": "Browse services",
    "gallery.cta.desc": "Every photo in this gallery started with a conversation. Let's have yours.",
    "gallery.cta.title": "Your space could be next.",
    "gallery.eyebrow": "Recent Work",
    "gallery.filters.all": "All",
    "gallery.subtitle": "A glimpse into the rooms, offices, and venues we've recently brought back to life.",
    "gallery.title": "Spaces we've transformed",
    "gallery.title1": "Modern Kitchen Reset",
    "gallery.title2": "Open-Plan Office",
    "gallery.title3": "Sunlit Living Room",
    "gallery.title4": "Corporate Suite",
    "gallery.title5": "Spa-Grade Bathroom",
    "gallery.title6": "Boardroom Refresh",
    "gallery.title7": "Hardwood Revival",
    "gallery.title8": "Restaurant Dining",
    "hero.cta1": "Book a Free Walkthrough",
    "hero.cta2": "Explore Services",
    "hero.eyebrow": "Trusted by 500+ Düsseldorf clients",
    "hero.scroll": "Scroll",
    "hero.stat1.label": "Happy Clients",
    "hero.stat1.num": "500",
    "hero.stat2.label": "Years Experience",
    "hero.stat2.num": "15",
    "hero.stat3.label": "Satisfaction",
    "hero.stat3.num": "100",
    "hero.subtitle": "We are BlitzBlank — a boutique cleaning studio delivering five-star residential and commercial cleaning across Düsseldorf. Spotless results, every visit, guaranteed in writing.",
    "hero.title1": "Immaculate spaces,",
    "hero.title2": "crafted with",
    "hero.title3": "obsessive care.",
    "legal.demo": "Note: BlitzBlank is a fictional demonstration project. All details on this page are placeholders and do not refer to a real company.",
    "legal.eyebrow": "Legal",
    "legal.imprint.contact.h": "Contact",
    "legal.imprint.copyright.h": "Copyright",
    "legal.imprint.copyright.p": "The content and works on these pages are subject to German copyright law. Reproduction, editing, distribution, or any use beyond what copyright permits requires the written consent of the respective author. Photography is embedded from Unsplash under the Unsplash License.",
    "legal.imprint.country": "Germany",
    "legal.imprint.dispute.h": "Consumer dispute resolution",
    "legal.imprint.dispute.p": "We are neither willing nor obliged to participate in dispute resolution proceedings before a consumer arbitration board (§ 36 VSBG).",
    "legal.imprint.editor.h": "Responsible for content under § 18 (2) MStV",
    "legal.imprint.editor.p": "Amélie Laurent, Königsallee 42, 40212 Düsseldorf",
    "legal.imprint.liability.h": "Liability for content",
    "legal.imprint.liability.p": "As a service provider we are responsible for our own content on these pages under general law (§ 7 (1) DDG). We are not, however, obliged to monitor transmitted or stored third-party information or to investigate circumstances indicating illegal activity (§§ 8–10 DDG). Obligations to remove or block the use of information under general law remain unaffected; liability is possible only from the moment we become aware of a concrete infringement.",
    "legal.imprint.links.h": "Liability for links",
    "legal.imprint.links.p": "This site contains links to external third-party websites over whose content we have no influence. The respective provider is always responsible for the content of linked pages. The links were checked for possible legal violations at the time of linking; should we become aware of an infringement, we will remove the affected link promptly.",
    "legal.imprint.owner": "Owner: Amélie Laurent",
    "legal.imprint.provider.h": "Information under § 5 DDG",
    "legal.imprint.subtitle": "Provider identification and legal information under § 5 DDG.",
    "legal.imprint.title": "Legal Notice",
    "legal.imprint.vat.h": "VAT ID",
    "legal.imprint.vat.p": "VAT identification number under § 27 a of the German VAT Act: DE999999999 (placeholder).",
    "legal.privacy.contact.h": "Contact by email or phone",
    "legal.privacy.contact.p": "If you contact us by email or phone, your message and the contact details you provide are processed solely to handle your request and any follow-up questions (Art. 6 (1) (b) GDPR, or Art. 6 (1) (f) GDPR for general enquiries).",
    "legal.privacy.controller.h": "Controller",
    "legal.privacy.controller.p": "The controller responsible for data processing on this website is:",
    "legal.privacy.cookies.h": "Cookies, tracking, and analytics",
    "legal.privacy.cookies.p": "This website sets no cookies, uses no analytics services, and embeds no tracking of any kind. Nothing is stored in your browser.",
    "legal.privacy.fonts.h": "Google Fonts",
    "legal.privacy.fonts.p": "This site loads the typeface Inter from Google Fonts (Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland). When a page loads, your browser requests the font files from Google's servers, which necessarily transmits your IP address to Google. We use Google Fonts in the interest of a consistent presentation of this website (Art. 6 (1) (f) GDPR). Details: https://policies.google.com/privacy.",
    "legal.privacy.form.h": "Contact form (FormSubmit)",
    "legal.privacy.form.p1": "The contact form transmits the details you enter (name, email address, phone number if given, selected service, and your message) via the form service FormSubmit (formsubmit.co), which relays them to our mailbox by email. We use this data solely to answer your request; it is not shared beyond that.",
    "legal.privacy.form.p2": "The legal basis is the consent you give via the checkbox (Art. 6 (1) (a) GDPR) and, where your request is aimed at a contract, Art. 6 (1) (b) GDPR. You may withdraw your consent at any time with effect for the future by emailing us.",
    "legal.privacy.hosting.h": "Hosting (GitHub Pages)",
    "legal.privacy.hosting.p1": "This website is hosted on GitHub Pages, a service of GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. When you visit the site, GitHub processes technical connection data — in particular your IP address — in server logs in order to deliver the pages and keep the service secure.",
    "legal.privacy.hosting.p2": "This processing is based on our legitimate interest in providing a reliable, secure website (Art. 6 (1) (f) GDPR). GitHub may transfer data to the USA; GitHub is certified under the EU-U.S. Data Privacy Framework. Details: https://docs.github.com/en/site-policy/privacy-policies.",
    "legal.privacy.images.h": "Embedded images (Unsplash)",
    "legal.privacy.images.p": "Photography on this site is embedded directly from Unsplash (Unsplash Inc., Montreal, Canada). Your browser requests these images from Unsplash's servers, which transmits your IP address to Unsplash (Art. 6 (1) (f) GDPR — consistent visual presentation of the site).",
    "legal.privacy.intro": "The protection of your personal data matters to us. This notice explains what personal data is processed when you visit this website or use the contact form, on what legal basis, and what rights you have. Personal data is any information relating to an identified or identifiable person.",
    "legal.privacy.retention.h": "Storage duration",
    "legal.privacy.retention.p": "We keep contact requests only as long as needed to handle them, and beyond that only where statutory retention duties require it. Server logs at GitHub are subject to GitHub's own retention periods.",
    "legal.privacy.rights.h": "Your rights",
    "legal.privacy.rights.l1": "Access to your stored data (Art. 15 GDPR)",
    "legal.privacy.rights.l2": "Rectification of inaccurate data (Art. 16 GDPR)",
    "legal.privacy.rights.l3": "Erasure (Art. 17 GDPR)",
    "legal.privacy.rights.l4": "Restriction of processing (Art. 18 GDPR)",
    "legal.privacy.rights.l5": "Data portability (Art. 20 GDPR)",
    "legal.privacy.rights.l6": "Objection to processing based on legitimate interest (Art. 21 GDPR)",
    "legal.privacy.rights.p": "Regarding your personal data, you have the right to:",
    "legal.privacy.rights.p2": "You also have the right to lodge a complaint with a data protection supervisory authority (Art. 77 GDPR) — for North Rhine-Westphalia: Landesbeauftragte für Datenschutz und Informationsfreiheit NRW, www.ldi.nrw.de.",
    "legal.privacy.subtitle": "What data this website processes, why — and the rights you have.",
    "legal.privacy.title": "Privacy Policy",
    "logo.tag": "Premium Reinigung",
    "nav.about": "About",
    "nav.close": "Close menu",
    "nav.contact": "Contact",
    "nav.cta": "Get a Quote",
    "nav.faq": "FAQ",
    "nav.gallery": "Gallery",
    "nav.home": "Home",
    "nav.menu": "Toggle menu",
    "nav.menuLabel": "Menu",
    "nav.reviews": "Reviews",
    "nav.services": "Services",
    "page.about.eyebrow": "About Us",
    "page.about.subtitle": "We're a small studio with big standards. Every clean is a chance to earn your trust — one detail at a time.",
    "page.about.title": "People who treat cleaning as a craft.",
    "page.contact.eyebrow": "Say Hello",
    "page.contact.subtitle": "Tell us what you need. We'll send a personalised quote within one business day — no pushy salespeople, no obligation.",
    "page.contact.title": "Let's make your space immaculate.",
    "page.gallery.eyebrow": "Portfolio",
    "page.gallery.subtitle": "A curated selection of recent projects. Filter by category, click any image to view full size.",
    "page.gallery.title": "Spaces we've brought back to life.",
    "page.services.eyebrow": "What We Do",
    "page.services.subtitle": "From boutique offices to sprawling warehouses, every BlitzBlank clean is held to the same uncompromising standard.",
    "page.services.title": "Ten services. One obsession.",
    "review.1.name": "Sarah Chen",
    "review.1.role": "COO, Northwind Studio",
    "review.1.text": "\"BlitzBlank has been cleaning our 8,000 sq ft office for two years now. Not a single complaint — only compliments from staff and clients alike. The crews are punctual, professional, and obsessed with detail. They found dust I didn't know existed.\"",
    "review.2.name": "Marcus Reed",
    "review.2.role": "Homeowner, Oberkassel",
    "review.2.text": "\"We tried three cleaning companies before finding BlitzBlank. The difference is night and day. They actually care. Our home has never felt more cared for, and the eco-friendly products give us peace of mind with two toddlers running around.\"",
    "review.3.name": "Elena Vasquez",
    "review.3.role": "Owner, Maison Verde",
    "review.3.text": "\"Running a busy restaurant means cleanliness is non-negotiable. BlitzBlank's after-hours team keeps our kitchen and dining room spotless, every single night. Health inspector said it was the cleanest kitchen she'd seen in a decade.\"",
    "review.4.name": "Dr. James Park",
    "review.4.role": "Director, Rheinland Family Clinic",
    "review.4.text": "\"Our medical clinic demands the highest sanitation standards. BlitzBlank's medical-grade cleaning protocol passes every audit without fail. Their team is discreet, professional, and impeccably trained. We've never had a single incident in five years.\"",
    "services.btn.quote": "Get a quote",
    "services.catalog.eyebrow": "Service Catalogue",
    "services.catalog.subtitle": "Ten specialised services, each delivered by trained crews using the right tools, the right products, and the right amount of obsession.",
    "services.catalog.title": "Pick the cleaning your space needs",
    "services.cta.btn1": "Talk to a specialist",
    "services.cta.btn2": "See our work",
    "services.cta.desc": "Tell us about your space and we'll recommend the right service, the right crew size, and the right cadence. Free, no obligation, no upsell.",
    "services.cta.title": "Not sure which service fits?",
    "services.details.eyebrow": "Service Details",
    "services.details.subtitle": "What's included, what you can expect, and why our crews are different.",
    "services.details.title": "A closer look at each service",
    "services.eyebrow": "What We Do",
    "services.link": "View details",
    "services.link.all": "Learn more",
    "services.process.eyebrow": "How It Works",
    "services.process.step1.desc": "Fill out our 60-second form. You'll get a flat-rate quote in writing — no phone tag, no upsells.",
    "services.process.step1.title": "Request a quote",
    "services.process.step2.desc": "Pick a date and time that works. Recurring clients get priority windows and locked-in rates.",
    "services.process.step2.title": "Schedule your clean",
    "services.process.step3.desc": "Your uniformed crew arrives on time, equipped, and trained. You get a checklist on completion.",
    "services.process.step3.title": "We do the work",
    "services.process.step4.desc": "Walk into a spotless space. Anything off? We return within 24 hours, free. That's our guarantee.",
    "services.process.step4.title": "Enjoy & relax",
    "services.process.title": "From quote to spotless in four steps",
    "services.subtitle": "From boutique offices to sprawling warehouses, we bring the same obsessive attention to detail to every job we touch.",
    "services.title": "Cleaning services for every space",
    "services.viewAll": "View all 10 services",
    "srv.carpet.desc": "Hot-water extraction lifts years of embedded dirt and allergens. Stains vanish, fibres fluff back to life.",
    "srv.carpet.title": "Carpet Cleaning",
    "srv.construction.desc": "Post-build and post-reno cleans. Dust extraction, debris removal, surface detailing — make it move-in ready.",
    "srv.construction.title": "Construction Cleaning",
    "srv.deep.desc": "A top-to-bottom reset for spaces that need serious attention. Baseboards, grout, behind appliances, light fixtures — everything.",
    "srv.deep.title": "Deep Cleaning",
    "srv.house.desc": "Reclaim your weekends. Our recurring house cleaning service keeps every corner of your home consistently spotless.",
    "srv.house.title": "House Cleaning",
    "srv.industrial.desc": "Warehouses, factories, and production floors cleaned to commercial-grade standards. Specialised equipment, trained crews.",
    "srv.industrial.title": "Industrial Cleaning",
    "srv.medical.desc": "Clinics, dental offices, urgent care. Hospital-grade terminal cleaning, trained crews, audit-ready always.",
    "srv.medical.title": "Medical Cleaning",
    "srv.moveout.desc": "Landlord-approved, deposit-saving cleans for vacating tenants. Includes interior appliances and cabinets.",
    "srv.moveout.title": "Move-out Cleaning",
    "srv.office.desc": "Keep your team focused and your clients impressed with daily, weekly, or nightly office cleaning tailored to your workflow.",
    "srv.office.title": "Office Cleaning",
    "srv.restaurant.desc": "After-hours kitchen, dining, and restroom cleaning that passes every health inspection. Hood & extractors included.",
    "srv.restaurant.title": "Restaurant Cleaning",
    "srv.window.desc": "Streak-free, sparkling windows inside and out — including hard-to-reach panes and skylights. Pure-water fed brush technology.",
    "srv.window.title": "Window Cleaning",
    "stats.1.label": "Happy Clients",
    "stats.1.num": "500",
    "stats.2.label": "Cleans Completed",
    "stats.2.num": "12500",
    "stats.3.label": "Years Experience",
    "stats.3.num": "15",
    "stats.4.label": "Satisfaction",
    "stats.4.num": "100",
    "stats.eyebrow": "By the Numbers",
    "stats.subtitle": "Fifteen years. Thousands of spotless rooms. A reputation earned one detail at a time.",
    "stats.title": "A track record you can trust",
    "strip.1": "Eco-Friendly Products",
    "strip.2": "Background-Checked Crews",
    "strip.3": "100% Satisfaction Guarantee",
    "strip.4": "Same-Day Availability",
    "strip.5": "Insured & Bonded",
    "testimonials.eyebrow": "Client Stories",
    "testimonials.subtitle": "A few of the kind words we've collected over the years.",
    "testimonials.title": "Loved by 500+ Düsseldorf clients",
    "value.1.desc": "We do what we said we'd do, exactly when we said we'd do it. If we mess up, we say so — and we fix it, fast, no excuses.",
    "value.1.title": "Integrity",
    "value.2.desc": "Cleaning is not a chore to us — it's a craft. We study tools, techniques, and chemistry so you don't have to think about any of it.",
    "value.2.title": "Craft",
    "value.3.desc": "We treat every space as if it were our own. Your home, your office, your restaurant — it matters to us because it matters to you.",
    "value.3.title": "Care",
    "value.4.desc": "You'll never have to wonder if we're showing up. Same crew, same time, same spotless result — visit after visit, year after year.",
    "value.4.title": "Reliability",
    "value.5.desc": "Plant-based products, refillable bottles, electric vehicles. We obsess over our environmental footprint as much as your dust bunnies.",
    "value.5.title": "Sustainability",
    "value.6.desc": "Our crews are employees, not contractors. They earn a living wage, get healthcare, and stay with us for years. You meet the same faces.",
    "value.6.title": "People First",
    "nav.lang": "Language",
    "nav.skip": "Skip to main content",
  },
  de: {
    "about.badge": "Durchschnittliche Bewertung aus 528 verifizierten Rezensionen",
    "about.certs.eyebrow": "Zertifikate",
    "about.certs.subtitle": "Das langweilige Papierkram, der Ihnen ruhigen Schlaf gibt. Haben wir alles erledigt.",
    "about.certs.title": "Zertifiziert, versichert, geprüft",
    "about.cta": "Team kennenlernen",
    "about.desc": "2010 in einer einzelnen Düsseldorfer Wohnung gegründet, ist BlitzBlank heute die leisest vertraute Reinigungsmanufaktur der Rhein-Ruhr-Region. Wir verzichten bewusst auf Franchising. Jedes Team wird intern eingestellt, geschult und ausgestattet — weil man Qualität nicht auslagern kann.",
    "about.exp.1.label": "Jahre im Geschäft",
    "about.exp.2.label": "Teammitglieder",
    "about.exp.3.label": "Reinigungen durchgeführt",
    "about.exp.4.label": "Kundentreue",
    "about.exp.eyebrow": "In Zahlen",
    "about.exp.title": "Fünfzehn Jahre, in Zahlen",
    "about.eyebrow": "Unsere Geschichte",
    "about.f1.desc": "Mit Hintergrundcheck, in Uniform und 80 Stunden geschult, bevor sie Ihren Raum betreten.",
    "about.f1.title": "Geprüfte Teams",
    "about.f2.desc": "Pflanzenbasierte, pH-neutrale Produkte — sicher für Kinder, Haustiere und den Planeten.",
    "about.f2.title": "Ökologie zuerst",
    "about.f3.desc": "Nicht zufrieden? Wir kommen innerhalb von 24 Stunden kostenlos zurück und machen es richtig.",
    "about.f3.title": "Echte Garantie",
    "about.f4.desc": "Festpreis-Angebot in 60 Sekunden online. Keine Überraschungen, keine Aufschläge.",
    "about.f4.title": "Transparente Preise",
    "about.head.eyebrow": "Über uns",
    "about.head.subtitle": "Unsere Mission, unsere Vision und die fünf Werte, an denen wir jede Entscheidung messen.",
    "about.head.title": "Das Team hinter dem Glanz",
    "about.mission.text": "Wir heben den Standard der Reinigung in jedem Zuhause und jedem Unternehmen, das wir betreuen — ein makelloser Raum ist kein Luxus, sondern die Grundlage für klareres Denken, ruhigeres Wohnen und produktiveres Arbeiten. Wir geben Menschen ihre Zeit zurück — und einen Raum, auf den sie stolz sind.",
    "about.mission.title": "Unsere Mission",
    "about.mv.eyebrow": "Was uns antreibt",
    "about.mv.subtitle": "Zwei kurze Sätze, die jede unserer Entscheidungen prägen.",
    "about.mv.title": "Mission & Vision",
    "about.team.eyebrow": "Die Menschen",
    "about.team.subtitle": "Die Crew hinter jedem makellosen Raum. Vor Ort — nicht am Schreibtisch.",
    "about.team.title": "Lernen Sie das Führungsteam kennen",
    "about.timeline.eyebrow": "Unser Weg",
    "about.timeline.subtitle": "Von einer einzelnen Düsseldorfer Wohnung zur leisest vertrauten Reinigungsmanufaktur der Rhein-Ruhr-Region.",
    "about.timeline.title": "Fünfzehn Jahre, eine Obsession",
    "about.title": "Eine Manufaktur, keine anonyme Kette.",
    "about.value.1.text": "Wir tun, was wir zugesagt haben — genau dann, wenn wir es zugesagt haben. Machen wir einen Fehler, sagen wir es und beheben ihn sofort, ohne Ausreden.",
    "about.value.1.title": "Integrität",
    "about.value.2.text": "Reinigung ist für uns keine Pflicht, sondern ein Handwerk. Wir studieren Werkzeuge, Techniken und Chemie, damit Sie an nichts davon denken müssen.",
    "about.value.2.title": "Handwerk",
    "about.value.3.text": "Wir behandeln jeden Raum, als wäre er unser eigener. Ihr Zuhause, Ihr Büro, Ihr Restaurant — es ist uns wichtig, weil es Ihnen wichtig ist.",
    "about.value.3.title": "Sorgfalt",
    "about.value.4.text": "Sie müssen sich nie fragen, ob wir kommen. Gleiches Team, gleiche Zeit, gleiches makelloses Ergebnis — Besuch für Besuch, Jahr für Jahr.",
    "about.value.4.title": "Verlässlichkeit",
    "about.value.5.text": "Pflanzenbasierte Produkte, nachfüllbare Flaschen, Elektrofahrzeuge. Unser ökologischer Fußabdruck beschäftigt uns genauso wie Ihr Staub.",
    "about.value.5.title": "Nachhaltigkeit",
    "about.values.eyebrow": "Wofür wir stehen",
    "about.values.subtitle": "Das sind keine Plakate an der Wand. Es sind die Filter, durch die jede Entscheidung läuft.",
    "about.values.title": "Fünf Werte, täglich gelebt",
    "about.vision.text": "Die leise vertrauteste Reinigungsmanufaktur der Rhein-Ruhr-Region zu werden — bekannt nicht durch lautes Marketing, sondern durch das Können unserer Teams, die Gründlichkeit unserer Ausbildung und die Beziehungen zu unseren Kunden.",
    "about.vision.title": "Unsere Vision",
    "contact.address.label": "Studio-Zentrale",
    "contact.details.desc": "Lieber erst sprechen? Rufen Sie uns an, schreiben Sie uns oder besuchen Sie unsere Zentrale in Düsseldorf. Wir beantworten jede Nachricht selbst — keine Chatbots, keine Callcenter.",
    "contact.details.eyebrow": "Kontaktdaten",
    "contact.details.title": "Echte Menschen, schnelle Antworten.",
    "contact.email.label": "E-Mail",
    "contact.faq.btn1": "Zum FAQ",
    "contact.faq.btn2": "Leistungen ansehen",
    "contact.faq.desc": "Stöbern Sie in unseren am häufigsten gestellten Fragen — Produkte, Termine, Garantien und mehr.",
    "contact.faq.title": "Zuerst eine kurze Frage?",
    "contact.form.consent": "Ich stimme zu, bezüglich meiner Anfrage kontaktiert zu werden, und akzeptiere die",
    "contact.form.consent.cont": "Ihre Daten geben wir niemals weiter.",
    "contact.form.consent.privacy": "Datenschutzerklärung",
    "contact.form.desc": "Felder mit * sind Pflichtfelder. Wir antworten innerhalb eines Werktages.",
    "contact.form.email": "E-Mail",
    "contact.form.firstName": "Vorname",
    "contact.form.lastName": "Nachname",
    "contact.form.message": "Erzählen Sie uns von Ihrem Raum",
    "contact.form.message.ph": "Quadratmeter, Frequenz, besondere Anforderungen…",
    "contact.form.phone": "Telefon",
    "contact.form.service": "Gewünschte Leistung",
    "contact.form.service.choose": "Bitte wählen…",
    "contact.form.service.other": "Sonstiges / Unsicher",
    "contact.form.submit": "Anfrage senden",
    "contact.form.title": "Kostenloses Angebot anfordern",
    "contact.hours.label": "Geschäftszeiten",
    "contact.hours.value": "Mo–Sa: 07:00 – 20:00 Uhr",
    "contact.hours.value2": "Sonntag: Geschlossen (nur Notfälle)",
    "contact.map.eyebrow": "Finden Sie uns",
    "contact.map.parking": "Parkplätze in der Nähe",
    "contact.map.subtitle": "Kommen Sie auf einen Kaffee vorbei oder vereinbaren Sie eine Tour durch das Studio, in dem jede Reinigung beginnt.",
    "contact.map.title": "Unsere Zentrale an der Königsallee",
    "contact.phone.label": "Telefon",
    "crumb.home": "Start",
    "crumb.label": "Brotkrümelnavigation",
    "cta.btn1": "Kostenloses Angebot",
    "cta.btn2": "Anrufen",
    "cta.desc": "Persönliches Angebot in unter 60 Sekunden. Unverbindlich, ohne Druck — einfach ein ehrliches Gespräch über Ihren Raum.",
    "cta.eyebrow": "Bereit, wenn Sie es sind",
    "cta.title": "Lassen Sie uns Ihren Raum makellos machen.",
    "error.btn1": "Zur Startseite",
    "error.btn2": "Leistungen ansehen",
    "error.btn3": "Kontakt",
    "error.code": "404",
    "error.desc": "Selbst unsere Teams können eine fehlende Seite nicht wegwischen. Der Link ist vielleicht kaputt oder die Seite wurde verschoben. Zurück zu einem makellosen Ort.",
    "error.suggest": "Oder probieren Sie einen davon",
    "error.suggest.about": "Über uns",
    "error.suggest.faq": "FAQ",
    "error.suggest.gallery": "Galerie",
    "error.suggest.reviews": "Bewertungen",
    "error.title": "Diese Seite ist uns entwischt.",
    "faq.1.a": "Absolut. Jedes Produkt in unserem Sortiment ist pflanzenbasiert, pH-neutral und nach EU-Ecolabel zertifiziert. Kein Chlor, kein Ammoniak, keine aggressiven Lösungsmittel. Unsere Teams werden geschult, alle Mittel verschlossen und außer Reichweite zu halten. Auf Wunsch bieten wir auch voll hypoallergene Optionen.",
    "faq.1.q": "Sind Ihre Reinigungsmittel sicher für Kinder und Haustiere?",
    "faq.2.a": "Überhaupt nicht. Die meisten unserer Kunden sind während der Reinigung bei der Arbeit. Wir nutzen sichere Schlüsselhaltungs-Protokolle, und jedes Teammitglied ist geprüft und bonitiert. Wenn Sie lieber anwesend sind — kein Problem. Unsere Teams sind freundlich, uniformiert und respektvoll.",
    "faq.2.q": "Muss ich während der Reinigung zu Hause sein?",
    "faq.3.a": "Jede Reinigung wird mit einer 100%-Zufriedenheitsgarantie backing. Wenn etwas nicht perfekt ist, kontaktieren Sie uns innerhalb von 24 Stunden — wir kommen kostenlos zurück und reinigen die betroffenen Bereiche nach. Ohne Fragen, ohne Verlegenheit. Diese Garantie gibt es seit 2010.",
    "faq.3.q": "Was passiert, wenn ich mit dem Ergebnis nicht zufrieden bin?",
    "faq.4.a": "Wir arbeiten mit Festpreisen auf Basis von Quadratmetern, Raumzahl und Umfang — nie nach Stunden. Sie erhalten innerhalb von 60 Sekunden ein schriftliches Angebot über unser Online-Formular. Der Preis, den Sie sehen, ist der Preis, den Sie zahlen. Keine Aufschläge, kein Trinkgeldzwang.",
    "faq.4.q": "Wie werden Ihre Preise berechnet?",
    "faq.5.a": "Ja — wöchentliche, vierzehntägige und monatliche Reinigungen sind unsere beliebtesten Pläne. Dauerkunden erhalten garantierte Preise, Prioritätsfenster und möglichst immer dasselbe Team. Sie können jederzeit mit 48 Stunden Vorankündigung pausieren, aussetzen oder stornieren — ohne Vertrag.",
    "faq.5.q": "Kann ich wiederkehrende Reinigungen vereinbaren?",
    "faq.6.a": "Ja, vollständig. BlitzBlank verfügt über 2 Mio. € Betriebshaftpflichtversicherung, Sozialversicherung für alle Mitarbeiter und eine Kautionsversicherung bei Diebstahl oder Schäden. Versicherungsscheine erhalten Sie auf Anfrage — wir nehmen Ihr Objekt gerne als zusätzlichen Versicherungsnehmer auf.",
    "faq.6.q": "Sind Sie versichert und bonitiert?",
    "faq.eyebrow": "Gut zu wissen",
    "faq.subtitle": "Alles, was Sie vor der Buchung wissen müssen. Noch Fragen? Schreiben Sie uns — wir freuen uns.",
    "faq.title": "Häufig gestellte Fragen",
    "footer.about": "Boutique-Reinigungsmanufaktur für Düsseldorf und die Rhein-Ruhr-Region seit 2010. Liebevolle Sorgfalt, ökologische Produkte, echte Menschen, die sich kümmern.",
    "footer.backToTop": "Nach oben",
    "footer.imprint": "Impressum",
    "footer.newsletter": "Kontakt halten",
    "footer.newsletterDesc": "Abonnieren Sie saisonale Reinigungstipps, exklusive Angebote und gelegentliche Inspiration. Kein Spam, versprochen.",
    "footer.placeholder": "Ihre E-Mail-Adresse",
    "footer.privacy": "Datenschutz",
    "footer.quickLinks": "Schnellzugriff",
    "footer.rights": "BlitzBlank. Alle Rechte vorbehalten.",
    "footer.services": "Leistungen",
    "footer.subscribe": "Abonnieren",
    "form.checked": "Bitte bestätigen Sie dieses Feld, um fortzufahren.",
    "form.email": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "form.errorMsg": "Bitte korrigieren Sie die markierten Felder und versuchen Sie es erneut.",
    "form.minLength": "Bitte mindestens {n} Zeichen eingeben.",
    "form.phone": "Bitte geben Sie eine gültige Telefonnummer ein.",
    "form.required": "Dieses Feld ist erforderlich.",
    "form.sendError": "Ihre Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es gleich noch einmal oder schreiben Sie uns direkt eine E-Mail.",
    "form.subject": "Neue Kontaktanfrage über blitzblank.de",
    "form.successMsg": "Vielen Dank! Ihre Nachricht wurde gesendet. Wir melden uns innerhalb eines Werktages.",
    "form.toast.invalid": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    "form.toast.sendError": "Senden fehlgeschlagen — bitte erneut versuchen.",
    "form.toast.subscribed": "Sie sind dabei! Herzlich willkommen.",
    "form.toast.success": "Nachricht erfolgreich gesendet!",
    "gallery.cat1": "Privat",
    "gallery.cat2": "Gewerbe",
    "gallery.cat3": "Tiefenreinigung",
    "gallery.cat4": "Bodenpflege",
    "gallery.cat5": "Gastronomie",
    "gallery.cta": "Galerie ansehen",
    "gallery.cta.btn1": "Projekt starten",
    "gallery.cta.btn2": "Leistungen ansehen",
    "gallery.cta.desc": "Jedes Foto in dieser Galie begann mit einem Gespräch. Führen wir auch Ihres.",
    "gallery.cta.title": "Ihr Raum könnte der Nächste sein.",
    "gallery.eyebrow": "Aktuelle Arbeiten",
    "gallery.filters.all": "Alle",
    "gallery.subtitle": "Ein Einblick in die Räume, Büros und Locations, die wir kürzlich neu belebt haben.",
    "gallery.title": "Räume, die wir verwandelt haben",
    "gallery.title1": "Moderne Küche",
    "gallery.title2": "Großraumbüro",
    "gallery.title3": "Sonnendurchflutetes Wohnzimmer",
    "gallery.title4": "Business-Suite",
    "gallery.title5": "Wellness-Bad",
    "gallery.title6": "Konferenzraum",
    "gallery.title7": "Parkett-Auffrischung",
    "gallery.title8": "Restaurant-Gastraum",
    "hero.cta1": "Kostenlose Besichtigung",
    "hero.cta2": "Leistungen entdecken",
    "hero.eyebrow": "Vertraut von über 500 Düsseldorfer Kunden",
    "hero.scroll": "Scrollen",
    "hero.stat1.label": "Zufriedene Kunden",
    "hero.stat1.num": "500",
    "hero.stat2.label": "Jahre Erfahrung",
    "hero.stat2.num": "15",
    "hero.stat3.label": "Zufriedenheit",
    "hero.stat3.num": "100",
    "hero.subtitle": "Wir sind BlitzBlank — eine boutique Reinigungsmanufaktur, die fünf-Sterne-Reinigung für Privatkunden und Unternehmen in ganz Düsseldorf liefert. Tadellose Ergebnisse, bei jedem Termin, schriftlich garantiert.",
    "hero.title1": "Makellose Räume,",
    "hero.title2": "geschaffen mit",
    "hero.title3": "liebevoller Sorgfalt.",
    "legal.demo": "Hinweis: BlitzBlank ist ein fiktives Demonstrationsprojekt. Alle Angaben auf dieser Seite sind Platzhalter und bezeichnen kein reales Unternehmen.",
    "legal.eyebrow": "Rechtliches",
    "legal.imprint.contact.h": "Kontakt",
    "legal.imprint.copyright.h": "Urheberrecht",
    "legal.imprint.copyright.p": "Die durch den Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors. Fotografien werden unter der Unsplash-Lizenz von Unsplash eingebunden.",
    "legal.imprint.country": "Deutschland",
    "legal.imprint.dispute.h": "Verbraucherstreitbeilegung",
    "legal.imprint.dispute.p": "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen (§ 36 VSBG).",
    "legal.imprint.editor.h": "Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV",
    "legal.imprint.editor.p": "Amélie Laurent, Königsallee 42, 40212 Düsseldorf",
    "legal.imprint.liability.h": "Haftung für Inhalte",
    "legal.imprint.liability.p": "Als Diensteanbieter sind wir gemäß § 7 Abs. 1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt; eine Haftung ist erst ab Kenntnis einer konkreten Rechtsverletzung möglich.",
    "legal.imprint.links.h": "Haftung für Links",
    "legal.imprint.links.p": "Diese Website enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter verantwortlich. Die Links wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft; bei Bekanntwerden von Rechtsverletzungen entfernen wir betroffene Links umgehend.",
    "legal.imprint.owner": "Inhaberin: Amélie Laurent",
    "legal.imprint.provider.h": "Angaben gemäß § 5 DDG",
    "legal.imprint.subtitle": "Anbieterkennzeichnung und rechtliche Hinweise gemäß § 5 DDG.",
    "legal.imprint.title": "Impressum",
    "legal.imprint.vat.h": "Umsatzsteuer-ID",
    "legal.imprint.vat.p": "Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE999999999 (Platzhalter).",
    "legal.privacy.contact.h": "Kontakt per E-Mail oder Telefon",
    "legal.privacy.contact.p": "Wenn Sie uns per E-Mail oder Telefon kontaktieren, verarbeiten wir Ihre Nachricht und die von Ihnen angegebenen Kontaktdaten ausschließlich zur Bearbeitung Ihres Anliegens und für Anschlussfragen (Art. 6 Abs. 1 lit. b DSGVO bzw. Art. 6 Abs. 1 lit. f DSGVO bei allgemeinen Anfragen).",
    "legal.privacy.controller.h": "Verantwortlicher",
    "legal.privacy.controller.p": "Verantwortlich für die Datenverarbeitung auf dieser Website ist:",
    "legal.privacy.cookies.h": "Cookies, Tracking und Analyse",
    "legal.privacy.cookies.p": "Diese Website setzt keine Cookies, nutzt keine Analysedienste und bindet keinerlei Tracking ein. In Ihrem Browser wird nichts gespeichert.",
    "legal.privacy.fonts.h": "Google Fonts",
    "legal.privacy.fonts.p": "Diese Website lädt die Schriftart Inter über Google Fonts (Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland). Beim Aufruf einer Seite lädt Ihr Browser die Schriftdateien von Google-Servern; dabei wird Ihre IP-Adresse zwangsläufig an Google übermittelt. Wir nutzen Google Fonts im Interesse einer einheitlichen Darstellung dieser Website (Art. 6 Abs. 1 lit. f DSGVO). Näheres: https://policies.google.com/privacy.",
    "legal.privacy.form.h": "Kontaktformular (FormSubmit)",
    "legal.privacy.form.p1": "Das Kontaktformular übermittelt die von Ihnen eingegebenen Angaben (Name, E-Mail-Adresse, ggf. Telefonnummer, gewählte Leistung und Ihre Nachricht) über den Formulardienst FormSubmit (formsubmit.co), der sie per E-Mail an unser Postfach weiterleitet. Wir verwenden diese Daten ausschließlich zur Beantwortung Ihrer Anfrage; eine Weitergabe darüber hinaus findet nicht statt.",
    "legal.privacy.form.p2": "Rechtsgrundlage ist Ihre über die Checkbox erteilte Einwilligung (Art. 6 Abs. 1 lit. a DSGVO) sowie, soweit Ihre Anfrage auf einen Vertrag zielt, Art. 6 Abs. 1 lit. b DSGVO. Sie können Ihre Einwilligung jederzeit mit Wirkung für die Zukunft per E-Mail widerrufen.",
    "legal.privacy.hosting.h": "Hosting (GitHub Pages)",
    "legal.privacy.hosting.p1": "Diese Website wird bei GitHub Pages gehostet, einem Dienst der GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. Beim Besuch der Website verarbeitet GitHub technische Verbindungsdaten — insbesondere Ihre IP-Adresse — in Server-Logs, um die Seiten auszuliefern und den Dienst abzusichern.",
    "legal.privacy.hosting.p2": "Die Verarbeitung erfolgt auf Grundlage unseres berechtigten Interesses an einem zuverlässigen und sicheren Betrieb der Website (Art. 6 Abs. 1 lit. f DSGVO). GitHub kann Daten in die USA übertragen; GitHub ist nach dem EU-U.S. Data Privacy Framework zertifiziert. Näheres: https://docs.github.com/en/site-policy/privacy-policies.",
    "legal.privacy.images.h": "Eingebundene Bilder (Unsplash)",
    "legal.privacy.images.p": "Fotografien auf dieser Website werden direkt von Unsplash (Unsplash Inc., Montreal, Kanada) eingebunden. Ihr Browser lädt diese Bilder von Unsplash-Servern; dabei wird Ihre IP-Adresse an Unsplash übermittelt (Art. 6 Abs. 1 lit. f DSGVO — einheitliche visuelle Darstellung der Website).",
    "legal.privacy.intro": "Der Schutz Ihrer persönlichen Daten ist uns wichtig. Diese Erklärung informiert darüber, welche personenbezogenen Daten beim Besuch dieser Website und bei der Nutzung des Kontaktformulars verarbeitet werden, auf welcher Rechtsgrundlage — und welche Rechte Ihnen zustehen. Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen.",
    "legal.privacy.retention.h": "Speicherdauer",
    "legal.privacy.retention.p": "Kontaktanfragen speichern wir nur so lange, wie es für die Bearbeitung erforderlich ist, danach nur, soweit gesetzliche Aufbewahrungspflichten bestehen. Für Server-Logs bei GitHub gelten die Speicherfristen von GitHub.",
    "legal.privacy.rights.h": "Ihre Rechte",
    "legal.privacy.rights.l1": "Auskunft über Ihre gespeicherten Daten (Art. 15 DSGVO)",
    "legal.privacy.rights.l2": "Berichtigung unrichtiger Daten (Art. 16 DSGVO)",
    "legal.privacy.rights.l3": "Löschung (Art. 17 DSGVO)",
    "legal.privacy.rights.l4": "Einschränkung der Verarbeitung (Art. 18 DSGVO)",
    "legal.privacy.rights.l5": "Datenübertragbarkeit (Art. 20 DSGVO)",
    "legal.privacy.rights.l6": "Widerspruch gegen Verarbeitung auf Grundlage berechtigter Interessen (Art. 21 DSGVO)",
    "legal.privacy.rights.p": "Ihnen stehen bezüglich Ihrer personenbezogenen Daten folgende Rechte zu:",
    "legal.privacy.rights.p2": "Außerdem haben Sie das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren (Art. 77 DSGVO) — für Nordrhein-Westfalen: Landesbeauftragte für Datenschutz und Informationsfreiheit NRW, www.ldi.nrw.de.",
    "legal.privacy.subtitle": "Welche Daten diese Website verarbeitet, warum — und welche Rechte Sie haben.",
    "legal.privacy.title": "Datenschutzerklärung",
    "logo.tag": "Premium Reinigung",
    "nav.about": "Über uns",
    "nav.close": "Menü schließen",
    "nav.contact": "Kontakt",
    "nav.cta": "Angebot anfordern",
    "nav.faq": "FAQ",
    "nav.gallery": "Galerie",
    "nav.home": "Start",
    "nav.menu": "Menü umschalten",
    "nav.menuLabel": "Menü",
    "nav.reviews": "Bewertungen",
    "nav.services": "Leistungen",
    "page.about.eyebrow": "Über uns",
    "page.about.subtitle": "Eine kleine Manufaktur mit großen Ansprüchen. Jede Reinigung ist die Chance, Ihr Vertrauen zu verdienen — Detail für Detail.",
    "page.about.title": "Menschen, die Reinigung als Handwerk verstehen.",
    "page.contact.eyebrow": "Sagen Sie Hallo",
    "page.contact.subtitle": "Sagen Sie uns, was Sie brauchen. Wir senden Ihnen innerhalb eines Werktages ein persönliches Angebot — ohne Drücker, ohne Verbindlichkeit.",
    "page.contact.title": "Lassen Sie uns Ihren Raum makellos machen.",
    "page.gallery.eyebrow": "Portfolio",
    "page.gallery.subtitle": "Eine kuratierte Auswahl aktueller Projekte. Nach Kategorie filtern, Bild anklicken für Vollbild.",
    "page.gallery.title": "Räume, die wir neu belebt haben.",
    "page.services.eyebrow": "Was wir tun",
    "page.services.subtitle": "Vom Boutique-Büro bis zur weitläufigen Halle — jede BlitzBlank-Reinigung folgt demselben kompromisslosen Standard.",
    "page.services.title": "Zehn Leistungen. Eine Obsession.",
    "review.1.name": "Sarah Chen",
    "review.1.role": "COO, Northwind Studio",
    "review.1.text": "„BlitzBlank reinigt seit zwei Jahren unser 800 m² großes Büro. Keine einzige Beschwerde — nur Komplimente von Team und Kunden. Die Crews sind pünktlich, professionell und bis ins Detail besessen. Sie haben Staub gefunden, von dem ich nichts wusste.\"",
    "review.2.name": "Marcus Reed",
    "review.2.role": "Privatkunde, Oberkassel",
    "review.2.text": "„Wir haben drei Reinigungsfirmen ausprobiert, bevor wir BlitzBlank fanden. Der Unterschied ist wie Tag und Nacht. Sie kümmern sich wirklich. Unser Zuhause war nie besser umsorgt — und die ökologischen Produkte geben uns mit zwei Kleinkindern Ruhe.\"",
    "review.3.name": "Elena Vasquez",
    "review.3.role": "Inhaberin, Maison Verde",
    "review.3.text": "„Ein Restaurant zu führen bedeutet: Sauberkeit ist nicht verhandelbar. Das After-Hours-Team von BlitzBlank hält Küche und Gastraum jede Nacht makellos. Der Gesundheitsinspektor sagte, es sei die sauberste Küche seit einem Jahrzehnt.\"",
    "review.4.name": "Dr. James Park",
    "review.4.role": "Leitender Arzt, Rheinland Familienpraxis",
    "review.4.text": "„Unsere Arztpraxis hat höchste Hygieneanforderungen. Das medizinische Reinigungsprotokoll von BlitzBlank besteht jede Prüfung beim ersten Versuch. Das Team ist diskret, professionell und tadellos geschult. In fünf Jahren kein einziger Vorfall.\"",
    "services.btn.quote": "Angebot anfordern",
    "services.catalog.eyebrow": "Leistungskatalog",
    "services.catalog.subtitle": "Zehn spezialisierte Leistungen, erbracht von geschulten Teams mit dem richtigen Werkzeug, den richtigen Produkten und der richtigen Portion Besessenheit.",
    "services.catalog.title": "Wählen Sie die passende Reinigung",
    "services.cta.btn1": "Mit Experten sprechen",
    "services.cta.btn2": "Unsere Arbeit ansehen",
    "services.cta.desc": "Erzählen Sie uns von Ihrem Raum — wir empfehlen die richtige Leistung, Teamgröße und Frequenz. Kostenlos, unverbindlich.",
    "services.cta.title": "Unsicher, welche Leistung passt?",
    "services.details.eyebrow": "Leistungsdetails",
    "services.details.subtitle": "Was enthalten ist, was Sie erwarten können, und warum unsere Teams anders sind.",
    "services.details.title": "Ein genauerer Blick auf jede Leistung",
    "services.eyebrow": "Was wir tun",
    "services.link": "Details ansehen",
    "services.link.all": "Mehr erfahren",
    "services.process.eyebrow": "So funktioniert's",
    "services.process.step1.desc": "Füllen Sie unser 60-Sekunden-Formular aus. Sie erhalten einen Festpreis-Angebot schriftlich — kein Telefon-Tennis, keine Aufschläge.",
    "services.process.step1.title": "Angebot anfordern",
    "services.process.step2.desc": "Wählen Sie Datum und Uhrzeit. Dauerkunden erhalten Prioritätsfenster und garantierte Preise.",
    "services.process.step2.title": "Termin vereinbaren",
    "services.process.step3.desc": "Ihr uniformiertes Team kommt pünktlich, ausgerüstet und geschult. Sie erhalten eine Checkliste bei Fertigstellung.",
    "services.process.step3.title": "Wir arbeiten",
    "services.process.step4.desc": "Betreten Sie einen makellosen Raum. Etwas nicht in Ordnung? Wir kommen innerhalb von 24 Stunden kostenlos zurück. Garantiert.",
    "services.process.step4.title": "Ankommen & entspannen",
    "services.process.title": "Vom Angebot zum makellosen Raum in vier Schritten",
    "services.subtitle": "Vom Boutique-Büro bis zur weitläufigen Halle — wir bringen jedem Auftrag dieselbe liebevolle Sorgfalt entgegen.",
    "services.title": "Reinigung für jeden Raum",
    "services.viewAll": "Alle 10 Leistungen ansehen",
    "srv.carpet.desc": "Heißwasserextraktion löst Jahre eingeschmutzter Partikel und Allergene. Flecken verschwinden, Fasern erstrahlen.",
    "srv.carpet.title": "Teppichreinigung",
    "srv.construction.desc": "Reinigung nach Bau und Renovierung. Staubabsaugung, Schuttentsorgung, Oberflächendetail — bezugsfertig.",
    "srv.construction.title": "Baureinigung",
    "srv.deep.desc": "Ein Komplett-Reset für Räume, die intensive Pflege brauchen. Sockelleisten, Fugen, hinter Geräten, Leuchten — alles.",
    "srv.deep.title": "Tiefenreinigung",
    "srv.house.desc": "Wochenenden zurückgewinnen. Unsere wiederkehrende Privatreinigung hält jede Ecke Ihres Zuhauses konsequent makellos.",
    "srv.house.title": "Privatreinigung",
    "srv.industrial.desc": "Lagerhallen, Fabriken und Produktionsflächen nach kommerziellem Standard. Spezialausrüstung, geschulte Teams.",
    "srv.industrial.title": "Industriereinigung",
    "srv.medical.desc": "Praxen, Zahnärzte, Notfallambulanzen. Krankenhausstandard, geschulte Teams, immer prüfbereit.",
    "srv.medical.title": "Medizinreinigung",
    "srv.moveout.desc": "Vom Vermieter akzeptierte, kautionsschonende Reinigung für ausziehende Mieter. Inklusive Geräten und Schränken.",
    "srv.moveout.title": "Auszugsreinigung",
    "srv.office.desc": "Tages-, wöchentliche oder nächtliche Büroreinigung — gehalten im Rhythmus Ihres Unternehmens. Ihr Team bleibt fokussiert, Ihre Kunden beeindruckt.",
    "srv.office.title": "Büroreinigung",
    "srv.restaurant.desc": "Reinigung nach Öffnungszeiten für Küche, Gastraum und Sanitäranlagen — jede Gesundheitsinspektion bestanden. Dunstabzug inklusive.",
    "srv.restaurant.title": "Gastronomiereinigung",
    "srv.window.desc": "Streifenfreie, funkelnde Fenster innen wie außen — inklusive schwer erreichbarer Scheiben und Oberlichter. Technik mit reinem Wasser.",
    "srv.window.title": "Fensterreinigung",
    "stats.1.label": "Zufriedene Kunden",
    "stats.1.num": "500",
    "stats.2.label": "Reinigungen durchgeführt",
    "stats.2.num": "12500",
    "stats.3.label": "Jahre Erfahrung",
    "stats.3.num": "15",
    "stats.4.label": "Zufriedenheit",
    "stats.4.num": "100",
    "stats.eyebrow": "In Zahlen",
    "stats.subtitle": "Fünfzehn Jahre. Tausende makellose Räume. Ein Ruf, der sich in jedem Detail verdient wird.",
    "stats.title": "Eine Bilanz, der man vertrauen kann",
    "strip.1": "Ökologische Produkte",
    "strip.2": "Geprüfte Mitarbeiter",
    "strip.3": "100% Zufriedenheitsgarantie",
    "strip.4": "Same-Day Verfügbarkeit",
    "strip.5": "Vollversichert",
    "testimonials.eyebrow": "Kundenstimmen",
    "testimonials.subtitle": "Einige der netten Worte, die wir im Laufe der Jahre gesammelt haben.",
    "testimonials.title": "Von über 500 Düsseldorfer Kunden geliebt",
    "value.1.desc": "Wir tun, was wir versprochen haben — genau dann, wenn wir es versprochen haben. Wenn etwas schiefgeht, sagen wir es. Und wir reparieren es, schnell, ohne Ausreden.",
    "value.1.title": "Integrität",
    "value.2.desc": "Reinigung ist für uns keine Pflicht — sie ist Handwerk. Wir studieren Werkzeuge, Techniken und Chemie, damit Sie sich darum keine Gedanken machen müssen.",
    "value.2.title": "Handwerk",
    "value.3.desc": "Wir behandeln jeden Raum, als wäre es unser eigener. Ihr Zuhause, Ihr Büro, Ihr Restaurant — es ist uns wichtig, weil es Ihnen wichtig ist.",
    "value.3.title": "Sorgfalt",
    "value.4.desc": "Sie werden sich nie fragen müssen, ob wir kommen. Gleiches Team, gleiche Zeit, gleiches makelloses Ergebnis — Termin für Termin, Jahr für Jahr.",
    "value.4.title": "Verlässlichkeit",
    "value.5.desc": "Pflanzenbasierte Produkte, nachfüllbare Flaschen, Elektrofahrzeuge. Wir sind so besessen von unserem ökologischen Fußabdruck wie von Ihren Staubflocken.",
    "value.5.title": "Nachhaltigkeit",
    "value.6.desc": "Unsere Teams sind Angestellte, keine Subunternehmer. Sie erhalten faire Löhne, Sozialleistungen und bleiben uns jahrelang erhalten. Sie sehen dieselben Gesichter.",
    "value.6.title": "Menschen zuerst",
    "nav.lang": "Sprache",
    "nav.skip": "Zum Hauptinhalt springen",
  },
};
